# Generated by Django 3.2.23 on 2023-11-16 13:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sinopse', models.TextField(max_length=1000)),
                ('classificacao', models.IntegerField(choices=[(10, 10), (12, 12), (14, 14), (16, 16), (18, 18)])),
                ('distribuidora', models.CharField(max_length=50)),
                ('thumb', models.ImageField(upload_to='thumb_animes')),
                ('background', models.ImageField(upload_to='bg_animes')),
                ('tipo', models.CharField(choices=[('LEGENDADO', 'Legendado'), ('DUBLADO', 'Dublado')], max_length=10)),
                ('generos', models.CharField(choices=[('ACAO', 'Ação'), ('ARTES_MARCIAIS', 'Artes Marciais'), ('AVENTURA', 'Aventura'), ('COMEDIA', 'Comédia'), ('DEMONIOS', 'Demônios'), ('DRAMA', 'Drama'), ('ECCHI', 'Ecchi'), ('ESCOLAR', 'Escolar'), ('ESPORTES', 'Esportes'), ('FANTASIA', 'Fantasia'), ('FICCAO_CIENTIFICA', 'Ficção Científica'), ('HAREM', 'Harém'), ('HISTORICO', 'Histórico'), ('HORROR', 'Horror'), ('JOGO', 'Jogo'), ('LIGHT_NOVEL', 'Light Novel'), ('MAGIA', 'Magia'), ('MECHA', 'Mecha'), ('MILITAR', 'Militar'), ('MISTERIO', 'Mistério'), ('MUSICAL', 'Musical'), ('ROMANCE', 'Romance'), ('SAMURAI', 'Samurai'), ('SEINEN', 'Seinen'), ('SEM_CENSURA', 'Sem Censura'), ('SHOUJO', 'Shoujo'), ('SHOUNEN', 'Shounen'), ('SLICE_OF_LIFE', 'Slice of Life'), ('SOBRENATURAL', 'Sobrenatural'), ('SUPER_PODERES', 'Super Poderes'), ('SUSPENSE', 'Suspense'), ('TERROR', 'Terror'), ('YAOI', 'Yaoi'), ('YURI', 'Yuri')], max_length=18)),
                ('temporada', models.CharField(choices=[('INVERNO', 'Inverno'), ('PRIMAVERA', 'Primavera'), ('VERAO', 'Verão'), ('OUTONO', 'Outono')], max_length=10)),
                ('visualizacoes', models.IntegerField(default=0)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
