# Generated by Django 4.2.7 on 2023-11-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='assistindo',
            field=models.ManyToManyField(related_name='assistindo', to='anime.anime'),
        ),
    ]
