# Generated by Django 4.2.7 on 2023-11-19 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='generos',
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generos', models.CharField(choices=[('ACAO', 'Ação'), ('ARTES_MARCIAIS', 'Artes Marciais'), ('AVENTURA', 'Aventura'), ('COMEDIA', 'Comédia'), ('DEMONIOS', 'Demônios'), ('DRAMA', 'Drama'), ('ECCHI', 'Ecchi'), ('ESCOLAR', 'Escolar'), ('ESPORTES', 'Esportes'), ('FANTASIA', 'Fantasia'), ('FICCAO_CIENTIFICA', 'Ficção Científica'), ('HAREM', 'Harém'), ('HISTORICO', 'Histórico'), ('HORROR', 'Horror'), ('JOGO', 'Jogo'), ('LIGHT_NOVEL', 'Light Novel'), ('MAGIA', 'Magia'), ('MECHA', 'Mecha'), ('MILITAR', 'Militar'), ('MISTERIO', 'Mistério'), ('MUSICAL', 'Musical'), ('ROMANCE', 'Romance'), ('SAMURAI', 'Samurai'), ('SEINEN', 'Seinen'), ('SEM_CENSURA', 'Sem Censura'), ('SHOUJO', 'Shoujo'), ('SHOUNEN', 'Shounen'), ('SLICE_OF_LIFE', 'Slice of Life'), ('SOBRENATURAL', 'Sobrenatural'), ('SUPER_PODERES', 'Super Poderes'), ('SUSPENSE', 'Suspense'), ('TERROR', 'Terror'), ('YAOI', 'Yaoi'), ('YURI', 'Yuri')], max_length=18)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generos', to='anime.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('video', models.URLField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodios', to='anime.anime')),
            ],
        ),
    ]
