# Generated by Django 4.2.7 on 2023-11-20 01:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_remove_anime_generos_genero_episodio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='background',
        ),
        migrations.AddField(
            model_name='episodio',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='episodio',
            name='thumb_episodio',
            field=models.ImageField(default='default_thumb.jpg', upload_to='thumb_episodios'),
        ),
    ]
