# Generated by Django 3.2.23 on 2023-11-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_remove_anime_background_episodio_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='generos',
            field=models.CharField(choices=[('Ação', 'ACAO'), ('ARTES_MARCIAIS', 'Artes Marciais'), ('AVENTURA', 'Aventura'), ('COMEDIA', 'Comédia'), ('DEMONIOS', 'Demônios'), ('DRAMA', 'Drama'), ('ECCHI', 'Ecchi'), ('ESCOLAR', 'Escolar'), ('ESPORTES', 'Esportes'), ('FANTASIA', 'Fantasia'), ('FICCAO_CIENTIFICA', 'Ficção Científica'), ('HAREM', 'Harém'), ('HISTORICO', 'Histórico'), ('HORROR', 'Horror'), ('JOGO', 'Jogo'), ('LIGHT_NOVEL', 'Light Novel'), ('MAGIA', 'Magia'), ('MECHA', 'Mecha'), ('MILITAR', 'Militar'), ('MISTERIO', 'Mistério'), ('MUSICAL', 'Musical'), ('ROMANCE', 'Romance'), ('SAMURAI', 'Samurai'), ('SEINEN', 'Seinen'), ('SEM_CENSURA', 'Sem Censura'), ('SHOUJO', 'Shoujo'), ('SHOUNEN', 'Shounen'), ('SLICE_OF_LIFE', 'Slice of Life'), ('SOBRENATURAL', 'Sobrenatural'), ('SUPER_PODERES', 'Super Poderes'), ('SUSPENSE', 'Suspense'), ('TERROR', 'Terror'), ('YAOI', 'Yaoi'), ('YURI', 'Yuri')], max_length=18),
        ),
    ]
